# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
    PYTHON: "C:\\conda"
    MINICONDA_VERSION: "latest"
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
    PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
    CONDA_CHANNELS: "sunpy"
    CONDA_DEPENDENCIES: "scipy matplotlib mock pandas requests beautifulsoup4 sqlalchemy scikit-image pytest-mock suds-jurko glymur drms hypothesis pytest-astropy"
    NUMPY_VERSION: "stable"
    ASTROPY_VERSION: "stable"
    PYTEST_VERSION: "<3.7"

  matrix:
    - PYTHON_VERSION: "2.7"
    - PYTHON_VERSION: "3.6"

platform: x64

os: Visual Studio 2017

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"
    - "conda remove --force pillow"
    - "pip install pillow"

# Not a .NET project, we build SunPy in the install step instead
build: false

test_script:
    - if %PYTHON_VERSION%==2.7 (%CMD_IN_ENV% python -m sunpy.data.sample)
    - "%CMD_IN_ENV% python setup.py test"
