skip-check: &skip-check
  name: Check for [ci skip]
  command: bash .circleci/early_exit.sh

apt-run: &apt-install
  name: Install apt packages
  command: |
    apt update
    apt install -y graphviz build-essential

docs-install: &docs-install
  name: Install Python dependencies
  command: |
    pip install -r requirements/docs.txt

version: 2
jobs:
  egg-info-27:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: python setup.py egg_info

  egg-info-35:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: python setup.py egg_info

  egg-info-36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: python setup.py egg_info

  egg-info-37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python setup.py egg_info

  pip3:
    docker:
      - image: continuumio/miniconda3
    steps:
      - restore_cache:
          keys: sample-data-v1

      - checkout
      - run: *skip-check
      - run: *apt-install
      - run:
          name: Update pip
          command: pip install -U pip
      - run:
          name: Install dependencies
          command: pip install --progress-bar off -e .[all]
      - run:
          name: Run tests
          command: python setup.py test

    environment:
          MPLBACKEND: agg
          COLUMNS: 180

  pip2:
    docker:
      - image: continuumio/miniconda2
    steps:
      - restore_cache:
          keys: sample-data-v1

      - checkout
      - run: *skip-check
      - run: *apt-install
      - run:
          name: Update pip
          command: pip install -U pip
      - run:
          name: Install dependencies
          command: pip install --progress-bar off -e .[all]
      - run:
          name: Run tests
          command: python setup.py test

    environment:
          MPLBACKEND: agg
          COLUMNS: 180

  32bit:
    docker:
      - image: quay.io/pypa/manylinux1_i686
    steps:
      - restore_cache:
          keys: sample-data-v1

      - checkout
      - run: *skip-check
      - run:
          name: yum dependencies
          command: yum install -y freetype freetype-devel libpng-devel tk
      - run:
          name: Install dependencies one
          command: /opt/python/cp36-cp36m/bin/pip install --progress-bar off numpy==1.15.3 scipy astropy matplotlib==1.5.3
      - run:
          name: Install dependencies two
          command: /opt/python/cp36-cp36m/bin/pip install --progress-bar off sqlalchemy scikit-image==0.13.1 glymur drms suds-jurko beautifulsoup4 requests python-dateutil pytest pytest-cov pytest-mock pytest-xdist mock hypothesis pytest-astropy pytest-rerunfailures
      - run:
          name: Run tests
          command: PYTHONHASHSEED=42 /opt/python/cp36-cp36m/bin/pytest -n=4
    environment:
          MPLBACKEND: agg
          COLUMNS: 180

  html-docs:
    docker:
      - image: continuumio/miniconda3
    steps:
      - restore_cache:
          keys: sample-data-v1

      - checkout
      - run: *skip-check
      - run: *apt-install
      - run: *docs-install
      - run: python setup.py build_docs -w
      - store_artifacts:
          path: docs/_build/html

      - run:
          name: "Built documentation is available at:"
          command: DOCS_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/docs/_build/html/index.html"; echo $DOCS_URL

      - save_cache:
          key: sample-data-v1
          paths:
            - ~/sunpy/data/sample_data


workflows:
  version: 2

  build-32:
    jobs:
      - 32bit

  pip-test:
    jobs:
      - pip3
      - pip2

  egg-info:
    jobs:
      - egg-info-37
      - egg-info-36
      - egg-info-35
      - egg-info-27

  test-documentation:
    jobs:
      - html-docs


notify:
  webhooks:
    - url: https://giles.cadair.com/circleci
